Readme: fix the "Reading" example
Due to missing quotes, it produced the following error, rather than the expected trace:

```
Error: Error#422: Expected " at character 70 in ... }, { "flag": false,   ---->  f  <----  oo: 4 }]} @ tink.json.BasicParser.die:237
```

Also, the field order of the traced object is different (and apparently consistently so across different targets, although formatting is a bit different), so I updated that too.